version: '3.8'

services:
  db:
    image: postgres:15
    container_name: proxibanque-postgres
    environment:
      POSTGRES_DB: hibernate_db
      POSTGRES_USER: hibernate_user
      POSTGRES_PASSWORD: hibernate_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
